substitutions:
  name: csi
  friendly_name: sensor CSI

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  project:
    name: esphome.csi-sensor
    version: "1.0"
globals:
  - id: threshold_val
    type: float
    restore_value: yes
    initial_value: '0'


external_components:
  # use all components from a local folder
  - source:
      type: local
      path: components

esp32:
  board: esp32-c6-devkitc-1
  variant: esp32c6
  framework:
    type: esp-idf
    #Can be dev, latest, recommended, or check https://github.com/espressif/esp-idf/releases
    version: "5.3.1"
    #check platform_version @ https://github.com/platformio/platform-espressif32/releases/
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESP_WIFI_CSI_ENABLED: y

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "CSI Hotspot"
    password: "csiforuandme"

captive_portal:

api:
logger:
ota:
  platform: esphome

binary_sensor:


wifi_csi:
  id: csi_motion
  name: Motion
  threshold: 0.6

  